name: Hub
author: nadjiebDunk (Reaploder)
main: hub\main
api: 4.0.0
version: 1.0

commands:
  hub:
    description: tp to lobby
    permission: hub.cmd

permissions:
  hub.cmd:
    default: true
